# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pinset.xdc

# Block Designs: bd/DPRAM/DPRAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPRAM || ORIG_REF_NAME==DPRAM}]

# IP: bd/DPRAM/ip/DPRAM_blk_mem_gen_0_0/DPRAM_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPRAM_blk_mem_gen_0_0 || ORIG_REF_NAME==DPRAM_blk_mem_gen_0_0}]

# Block Designs: bd/CLK/CLK.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLK || ORIG_REF_NAME==CLK}]

# IP: bd/CLK/ip/CLK_clk_wiz_0_0/CLK_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLK_clk_wiz_0_0 || ORIG_REF_NAME==CLK_clk_wiz_0_0}]

# XDC: bd/DPRAM/ip/DPRAM_blk_mem_gen_0_0/DPRAM_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/DPRAM/DPRAM_ooc.xdc

# XDC: bd/CLK/ip/CLK_clk_wiz_0_0/CLK_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CLK_clk_wiz_0_0 || ORIG_REF_NAME==CLK_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/CLK/ip/CLK_clk_wiz_0_0/CLK_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CLK_clk_wiz_0_0 || ORIG_REF_NAME==CLK_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/CLK/ip/CLK_clk_wiz_0_0/CLK_clk_wiz_0_0_ooc.xdc

# XDC: bd/CLK/CLK_ooc.xdc
